name: Deploy Spring Boot to Minikube

on:
  workflow_dispatch: 

jobs:
  configcheck:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Show Minikube Status
      run: |
        minikube status
        kubectl config current-context
    deployconfig:
    runs-on: ubuntu-latest
    needs: build  # 👈 Runs *after* the build job completes
    steps:
      - name: deploy configuration
        run: |
             kubectl apply -f db-config.yaml