name: Deploy Spring Boot to Minikube

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show Minikube Status
      run: |
        minikube status
        kubectl config current-context
    - name: Apply Kubernetes Pod
      run: |
        kubectl apply -f db-config.yaml
      run: |
        kubectl apply -f mysql-secrets.yaml
      run: |
        kubectl apply -f db-deployment.yaml
      run: |
        kubectl apply -f app-deployment.yaml
    - name: Verify Pod Status
      run: |
        kubectl get pods